name: icon-automation
on:
  push:
    branches:
      - main
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      # - run: npm install
      
      - name: List directory contents
        run:  ls -l src
      - name: Build and Publish
        uses: Kinsey-LKJ/iconFlow-Action@main
        with:
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: List directory contents
        run:  ls -l src
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
