name: icon-automation
on:
  push:
    branches:
      - 'iconflow-*'
    paths:
      - 'package.json'

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build and Publish
        uses: Kinsey-LKJ/iconFlow-Action@main
        with:
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          figma-file-url: ${{ secrets.FIGMA_FILE_URL }}
          figma-token: ${{ secrets.FIGMA_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
