name: icon-automation
on:
  push:
    branches:
    - main
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: npm install
    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./src/"
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
    - run: npm run generate
    - run: npm run  build:bundle
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: npm run build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
